/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.screens;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author artur
 */
public class eliminarPanel extends javax.swing.JPanel {
    Connection conn;
    String url = "jdbc:sqlite:C:\\Users\\artur\\Documents\\NetBeansProjects\\rhproyec\\src\\db_data\\data.db";

    /**
     * Creates new form eliminarPanel
     */
    public eliminarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconrhmu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        motivo = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        area = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 35, 35));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(1546, 876));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconrhmu.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        iconrhmu.setForeground(new java.awt.Color(255, 255, 255));
        iconrhmu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconrhmu.png"))); // NOI18N
        iconrhmu.setText("RH-MU El control es poder...");
        iconrhmu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(iconrhmu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1050, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar trabajador dentro de la base de datos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 70, 70));

        motivo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        motivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/motivo3.png"))); // NOI18N
        motivo.setPreferredSize(new java.awt.Dimension(1370, 411));
        jPanel1.add(motivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1550, 240));

        idLabel.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        idLabel.setText("ID");
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        nombreLabel.setText("Nombre");
        jPanel1.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 130, 40));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 380, 40));

        buscarButton.setBackground(new java.awt.Color(35, 81, 146));
        buscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 170, -1));

        eliminarButton.setBackground(new java.awt.Color(35, 81, 146));
        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        eliminarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarButtonMousePressed(evt);
            }
        });
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 170, -1));

        area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaActionPerformed(evt);
            }
        });
        jPanel1.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 130, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel5.setText("AREA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        try {
            conn = DriverManager.getConnection(url);
            if (conn!=null) {
                PreparedStatement stmt = conn.prepareStatement("SELECT * FROM trabajador WHERE id =?");
                stmt.setInt(1, Integer.valueOf(id.getText()));
                ResultSet rs = stmt.executeQuery();
                String area = rs.getString("area");
                String nombre = rs.getString("nombres")+" "+ rs.getString("apellidoP")+" "+rs.getString("apellidoM");
                this.nombre.setText(nombre);
                this.area.setText(area);
            }
        } catch (Exception e) {
            System.out.println("Error "+ e.getMessage());
        } finally {
            try {
                if (conn!=null) {
                    conn.close();
                }
            } catch (Exception e) {
                System.out.println("Error "+e.getMessage());
            }
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void eliminarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarButtonMousePressed
        // TODO add your handling code here:
        try {
            conn = DriverManager.getConnection(url);
            if (conn!=null) {
                PreparedStatement stmt1 = conn.prepareStatement("SELECT * FROM trabajador WHERE id =?");
                PreparedStatement stmt = conn.prepareStatement("DELETE FROM trabajador WHERE id =?");
                stmt1.setInt(1, Integer.valueOf(id.getText()));
                stmt.setInt(1, Integer.valueOf(id.getText()));
                ResultSet rs = stmt1.executeQuery();
                
                String nombre = rs.getString("nombres")+" "+ rs.getString("apellidoP")+" "+rs.getString("apellidoM");
                JOptionPane.showMessageDialog(null, "Eliminado: "+nombre, "Registro", 0);
                stmt.executeUpdate();
            }
        } catch (Exception e) {
            System.out.println("Error "+ e.getMessage());
        } finally {
            try {
                if (conn!=null) {
                    conn.close();
                }
            } catch (Exception e) {
                System.out.println("Error "+e.getMessage());
            }
        }
    }//GEN-LAST:event_eliminarButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel iconrhmu;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel motivo;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreLabel;
    // End of variables declaration//GEN-END:variables
}
