/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.screens;


import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import desplazable.Desface;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Image;
import javax.swing.Icon;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.sql.*;

/**
 *
 * @author artur
 */
public class homeFrame extends javax.swing.JFrame {
    Desface desplace;
    Desface desplace2;
    panelAnadir p = new panelAnadir();
    String url = "jdbc:sqlite:C:\\Users\\artur\\Documents\\NetBeansProjects\\rhproyec\\src\\db_data\\data.db";
    Connection conn;
    eliminarPanel p2 = new eliminarPanel();
    modificarPanel p3 = new modificarPanel();
    
    private ImageIcon imagen; private Icon icono;
    /**
     * Creates new form homeFrame
     */
    public homeFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/favicon.png"));
        setIconImage(icon.getImage());
        desplace = new Desface();
        desplace2 = new Desface();
        resize(this.rightPanel.getWidth()-100, this.rightPanel.getHeight()-100, wallpaper, "src/img/wallpaper.png");
        this.rightPanel.setVisible(false);
        
        
        
        
        
        
        
        
    }
    
    public void setUser(String user){
        nombre.setText(user);
    }
    private void visible(boolean state){
        bienvenido.setVisible(state);
        nombre.setVisible(state);
        homeLabel.setVisible(state);
        anadirLabel.setVisible(state);
        eliminarLabel.setVisible(state);
        modificarLabel.setVisible(state);
    }
    private void resize (int width, int height, JLabel lbl, String root){
        ImageIcon img = new ImageIcon(root);
        ImageIcon ico = new ImageIcon(img.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        lbl.setSize(width, height);
        lbl.setIcon(ico);
        this.repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        todo = new javax.swing.JPanel();
        leftLabel = new Clases.PanelRound();
        bienvenido = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        desplegar = new javax.swing.JLabel();
        homeLabel = new Clases.PanelRound();
        home = new javax.swing.JLabel();
        anadirLabel = new Clases.PanelRound();
        anadir = new javax.swing.JLabel();
        eliminarLabel = new Clases.PanelRound();
        eliminar = new javax.swing.JLabel();
        modificarLabel = new Clases.PanelRound();
        modificar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        wallpaper = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(35, 35, 35));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        bg.setBackground(new java.awt.Color(35, 35, 35));
        bg.setPreferredSize(new java.awt.Dimension(1280, 720));

        todo.setBackground(new java.awt.Color(35, 35, 35));

        javax.swing.GroupLayout todoLayout = new javax.swing.GroupLayout(todo);
        todo.setLayout(todoLayout);
        todoLayout.setHorizontalGroup(
            todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        todoLayout.setVerticalGroup(
            todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        leftLabel.setBackground(new java.awt.Color(35, 81, 146));
        leftLabel.setPreferredSize(new java.awt.Dimension(300, 720));
        leftLabel.setRoundBottomRight(30);
        leftLabel.setRoundTopRight(30);

        bienvenido.setFont(new java.awt.Font("Century Gothic", 0, 39)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        bienvenido.setText("Bienvenido");

        nombre.setFont(new java.awt.Font("Century Gothic", 0, 28)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Nombre");
        nombre.setToolTipText("");

        desplegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rightArrow.png"))); // NOI18N
        desplegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desplegar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desplegarMousePressed(evt);
            }
        });

        homeLabel.setBackground(new java.awt.Color(35, 81, 146));
        homeLabel.setRoundBottomRight(18);
        homeLabel.setRoundTopRight(18);
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeLabelMousePressed(evt);
            }
        });

        home.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HomeIcon.png"))); // NOI18N
        home.setText("Home   ");
        home.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout homeLabelLayout = new javax.swing.GroupLayout(homeLabel);
        homeLabel.setLayout(homeLabelLayout);
        homeLabelLayout.setHorizontalGroup(
            homeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home)
                .addGap(27, 27, 27))
        );
        homeLabelLayout.setVerticalGroup(
            homeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLabelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        anadirLabel.setBackground(new java.awt.Color(35, 81, 146));
        anadirLabel.setRoundBottomRight(18);
        anadirLabel.setRoundTopRight(18);
        anadirLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anadirLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                anadirLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                anadirLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                anadirLabelMousePressed(evt);
            }
        });

        anadir.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        anadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AddIcon.png"))); // NOI18N
        anadir.setText("Añadir  ");
        anadir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout anadirLabelLayout = new javax.swing.GroupLayout(anadirLabel);
        anadirLabel.setLayout(anadirLabelLayout);
        anadirLabelLayout.setHorizontalGroup(
            anadirLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anadirLabelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(anadir)
                .addContainerGap())
        );
        anadirLabelLayout.setVerticalGroup(
            anadirLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anadirLabelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(anadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        eliminarLabel.setBackground(new java.awt.Color(35, 81, 146));
        eliminarLabel.setRoundBottomRight(18);
        eliminarLabel.setRoundTopRight(18);
        eliminarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarLabelMousePressed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteIcon.png"))); // NOI18N
        eliminar.setText("Eliminar ");
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout eliminarLabelLayout = new javax.swing.GroupLayout(eliminarLabel);
        eliminarLabel.setLayout(eliminarLabelLayout);
        eliminarLabelLayout.setHorizontalGroup(
            eliminarLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLabelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminarLabelLayout.setVerticalGroup(
            eliminarLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLabelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );

        modificarLabel.setBackground(new java.awt.Color(35, 81, 146));
        modificarLabel.setRoundBottomRight(18);
        modificarLabel.setRoundTopRight(18);
        modificarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarLabelMousePressed(evt);
            }
        });

        modificar.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modifyIcon.png"))); // NOI18N
        modificar.setText("Mostrar");
        modificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout modificarLabelLayout = new javax.swing.GroupLayout(modificarLabel);
        modificarLabel.setLayout(modificarLabelLayout);
        modificarLabelLayout.setHorizontalGroup(
            modificarLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarLabelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(modificar)
                .addGap(28, 28, 28))
        );
        modificarLabelLayout.setVerticalGroup(
            modificarLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLabelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(modificar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/helpIcon.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout leftLabelLayout = new javax.swing.GroupLayout(leftLabel);
        leftLabel.setLayout(leftLabelLayout);
        leftLabelLayout.setHorizontalGroup(
            leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLabelLayout.createSequentialGroup()
                .addGroup(leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLabelLayout.createSequentialGroup()
                        .addGroup(leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(anadirLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(leftLabelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(bienvenido))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desplegar))
                    .addGroup(leftLabelLayout.createSequentialGroup()
                        .addGroup(leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(eliminarLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(modificarLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(leftLabelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(nombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftLabelLayout.setVerticalGroup(
            leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLabelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(bienvenido)
                .addGroup(leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftLabelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anadirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLabelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(desplegar)
                        .addGap(340, 340, 340))))
        );

        rightPanel.setBackground(new java.awt.Color(35, 35, 35));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallpaper.png"))); // NOI18N
        wallpaper.setMaximumSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(leftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(todo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addComponent(todo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowStateChanged

    private void homeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseEntered

       Color p = new Color(26,59,107);
        setCursor(Cursor.HAND_CURSOR);
        homeLabel.setBackground(p);
    }//GEN-LAST:event_homeLabelMouseEntered

    private void homeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        Color p = new Color(35,81,146);
        homeLabel.setBackground(p);
    }//GEN-LAST:event_homeLabelMouseExited

    private void anadirLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anadirLabelMouseEntered
        // TODO add your handling code here:
        Color p = new Color(26,59,107);
        setCursor(Cursor.HAND_CURSOR);
        anadirLabel.setBackground(p);
    }//GEN-LAST:event_anadirLabelMouseEntered

    private void anadirLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anadirLabelMouseExited
        // TODO add your handling code here
        setCursor(Cursor.DEFAULT_CURSOR);
        Color p = new Color(35,81,146);
        anadirLabel.setBackground(p);
    }//GEN-LAST:event_anadirLabelMouseExited

    private void eliminarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarLabelMouseEntered
        // TODO add your handling code here:
        Color p = new Color(26,59,107);
        setCursor(Cursor.HAND_CURSOR);
        eliminarLabel.setBackground(p);
    }//GEN-LAST:event_eliminarLabelMouseEntered

    private void eliminarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarLabelMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        Color p = new Color(35,81,146);
        eliminarLabel.setBackground(p);
    }//GEN-LAST:event_eliminarLabelMouseExited

    private void modificarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarLabelMouseEntered
        // TODO add your handling code here:
        Color p = new Color(26,59,107);
        setCursor(Cursor.HAND_CURSOR);
        modificarLabel.setBackground(p);
    }//GEN-LAST:event_modificarLabelMouseEntered

    private void modificarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarLabelMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        Color p = new Color(35,81,146);
        modificarLabel.setBackground(p);
    }//GEN-LAST:event_modificarLabelMouseExited

    private void desplegarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desplegarMousePressed
        // TODO add your handling code here:
        if (leftLabel.getX()==0) {
            
                desplace.desplazarIzquierda(leftLabel, leftLabel.getX(), -170, 10, 10);
                todo.setSize(todo.getWidth()+ 170, todo.getHeight());
                
                bienvenido.setForeground(leftLabel.getBackground());
                nombre.setForeground(leftLabel.getBackground());
                this.todo.setSize( todo.getWidth()+170, todo.getHeight());
                desplace2.desplazarIzquierda(todo, todo.getX(), todo.getX()-170, 10, 10);
                p.agrandar(170);
                System.out.println(todo.getSize());
                
            
            
        }else{
            desplace.desplazarDerecha(leftLabel, leftLabel.getX(), 0, 10, 10);
            todo.setSize(todo.getWidth()-170, todo.getHeight());
            bienvenido.setForeground(Color.WHITE);
            nombre.setForeground(Color.WHITE);
            desplace2.desplazarDerecha(todo, todo.getX(), todo.getX()+170, 10, 10);
            p.agrandar(-170);
            System.out.println(todo.getSize());
            
        }
        
        
        
    }//GEN-LAST:event_desplegarMousePressed

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_homeLabelMouseClicked

    private void homeLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMousePressed
        // TODO add your handling code here:
        
        
            rightPanel.setVisible(true);
            todo.setVisible(false);
            System.out.println(String.valueOf(todo.getSize()));
            
        
    }//GEN-LAST:event_homeLabelMousePressed

    private void anadirLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anadirLabelMousePressed
        // TODO add your handling code here:
        rightPanel.setVisible(false);
        todo.setVisible(true);
        
        p.setSize(todo.getWidth()+170, todo.getHeight());
        p.setLocation(0,0);
        
        todo.removeAll();
        todo.add(p,BorderLayout.CENTER);
        todo.revalidate();
        todo.repaint();
    }//GEN-LAST:event_anadirLabelMousePressed

    private void anadirLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anadirLabelMouseClicked
        // TODO add your handling code here:
        rightPanel.setVisible(false);
        todo.setVisible(true);
        
        p.setSize(todo.getWidth()+170, todo.getHeight());
        p.setLocation(0,0);
        
        todo.removeAll();
        todo.add(p,BorderLayout.CENTER);
        todo.revalidate();
        todo.repaint();
    }//GEN-LAST:event_anadirLabelMouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        try {
            try {
                // TODO add your handling code here:
                Desktop.getDesktop().browse(new URI("https://rhmu.waifusmod.com"));
            } catch (IOException ex) {
                Logger.getLogger(logScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(logScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void modificarLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarLabelMousePressed
        // TODO add your handling code here:
         rightPanel.setVisible(false);
        todo.setVisible(true);
        
        p3.setSize(todo.getWidth()+170, todo.getHeight());
        p3.setLocation(0,0);
        
        todo.removeAll();
        todo.add(p3,BorderLayout.CENTER);
        todo.revalidate();
        todo.repaint();
    }//GEN-LAST:event_modificarLabelMousePressed

    private void eliminarLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarLabelMousePressed
        // TODO add your handling code here:
        rightPanel.setVisible(false);
        todo.setVisible(true);
        
        p2.setSize(todo.getWidth()+170, todo.getHeight());
        p2.setLocation(0,0);
        
        todo.removeAll();
        todo.add(p2,BorderLayout.CENTER);
        todo.revalidate();
        todo.repaint();
    }//GEN-LAST:event_eliminarLabelMousePressed
    
    private void leftLabelsVisible(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
            FlatArcDarkIJTheme.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeFrame().setVisible(true);
            }
        });
        
    }
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anadir;
    private Clases.PanelRound anadirLabel;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel desplegar;
    private javax.swing.JLabel eliminar;
    private Clases.PanelRound eliminarLabel;
    private javax.swing.JLabel home;
    private Clases.PanelRound homeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private Clases.PanelRound leftLabel;
    private javax.swing.JLabel modificar;
    private Clases.PanelRound modificarLabel;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel todo;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
