/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.screens;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author artur
 */
public class logScreen extends javax.swing.JFrame {

    registrar p2 = new registrar();
    homeFrame p = new homeFrame();
    Connection conn;
    String url = "jdbc:sqlite:C:\\Users\\artur\\Documents\\NetBeansProjects\\rhproyec\\src\\db_data\\data.db";
    int xMouse,Ymouse;
    /**
     * Creates new form logScreen
     */
    public logScreen() {
        
        initComponents();
        setLocationRelativeTo(null); 
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/favicon.png"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        labelIcon = new javax.swing.JLabel();
        leftLabel = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        inciarSesion = new javax.swing.JLabel();
        userLabel = new javax.swing.JPanel();
        user = new javax.swing.JTextField();
        contrasenaLabel = new javax.swing.JPanel();
        contrasena = new javax.swing.JPasswordField();
        enterLabel = new javax.swing.JLabel();
        eslogan = new javax.swing.JLabel();
        jlabelUsuario = new javax.swing.JLabel();
        jlabelContrasena = new javax.swing.JLabel();
        registrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dragPanel = new javax.swing.JPanel();
        exitTarget = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        helpLabel = new javax.swing.JPanel();
        helpicon = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(53, 53, 53));
        bg.setFocusCycleRoot(true);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/labelicon.png"))); // NOI18N
        bg.add(labelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 420, 420));

        leftLabel.setBackground(new java.awt.Color(35, 81, 146));
        leftLabel.setPreferredSize(new java.awt.Dimension(265, 460));

        bienvenido.setBackground(new java.awt.Color(255, 255, 255));
        bienvenido.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        bienvenido.setText("Bienvenido");

        inciarSesion.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        inciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        inciarSesion.setText("Iniciar sesion");

        userLabel.setBackground(new java.awt.Color(53, 53, 53));
        userLabel.setPreferredSize(new java.awt.Dimension(137, 27));

        user.setBackground(new java.awt.Color(53, 53, 53));
        user.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Ingrese su usuario");
        user.setBorder(null);
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userMousePressed(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userLabelLayout = new javax.swing.GroupLayout(userLabel);
        userLabel.setLayout(userLabelLayout);
        userLabelLayout.setHorizontalGroup(
            userLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(userLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userLabelLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        userLabelLayout.setVerticalGroup(
            userLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
            .addGroup(userLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        contrasenaLabel.setBackground(new java.awt.Color(53, 53, 53));
        contrasenaLabel.setPreferredSize(new java.awt.Dimension(137, 27));

        contrasena.setBackground(new java.awt.Color(53, 53, 53));
        contrasena.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        contrasena.setForeground(new java.awt.Color(255, 255, 255));
        contrasena.setText("**********");
        contrasena.setBorder(null);
        contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout contrasenaLabelLayout = new javax.swing.GroupLayout(contrasenaLabel);
        contrasenaLabel.setLayout(contrasenaLabelLayout);
        contrasenaLabelLayout.setHorizontalGroup(
            contrasenaLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );
        contrasenaLabelLayout.setVerticalGroup(
            contrasenaLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        enterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flechaButton.png"))); // NOI18N
        enterLabel.setToolTipText("Entrar");
        enterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterLabelMousePressed(evt);
            }
        });

        eslogan.setFont(new java.awt.Font("Century Gothic", 2, 17)); // NOI18N
        eslogan.setForeground(new java.awt.Color(255, 255, 255));
        eslogan.setText("Control es poder...");

        jlabelUsuario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlabelUsuario.setText("Usuario");

        jlabelContrasena.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlabelContrasena.setForeground(new java.awt.Color(255, 255, 255));
        jlabelContrasena.setText("Contraseña");

        registrar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("¿No tienes cuenta?");
        registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registrarMousePressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout leftLabelLayout = new javax.swing.GroupLayout(leftLabel);
        leftLabel.setLayout(leftLabelLayout);
        leftLabelLayout.setHorizontalGroup(
            leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLabelLayout.createSequentialGroup()
                .addGroup(leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftLabelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasenaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bienvenido)
                            .addGroup(leftLabelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(inciarSesion))
                            .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelUsuario)
                            .addComponent(jlabelContrasena)))
                    .addGroup(leftLabelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(enterLabel))
                    .addGroup(leftLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eslogan)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLabelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addGap(73, 73, 73))
        );
        leftLabelLayout.setVerticalGroup(
            leftLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLabelLayout.createSequentialGroup()
                .addComponent(eslogan)
                .addGap(84, 84, 84)
                .addComponent(bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inciarSesion)
                .addGap(30, 30, 30)
                .addComponent(jlabelUsuario)
                .addGap(7, 7, 7)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contrasenaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterLabel)
                .addGap(18, 18, 18)
                .addComponent(registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        bg.add(leftLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 265, 460));

        dragPanel.setBackground(new java.awt.Color(53, 53, 53));
        dragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragPanelMouseDragged(evt);
            }
        });
        dragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragPanelMousePressed(evt);
            }
        });

        exitTarget.setBackground(new java.awt.Color(51, 51, 51));
        exitTarget.setForeground(new java.awt.Color(153, 0, 0));
        exitTarget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTargetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTargetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTargetMouseExited(evt);
            }
        });

        x.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        x.setText("X");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitTargetLayout = new javax.swing.GroupLayout(exitTarget);
        exitTarget.setLayout(exitTargetLayout);
        exitTargetLayout.setHorizontalGroup(
            exitTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(exitTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitTargetLayout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(x)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );
        exitTargetLayout.setVerticalGroup(
            exitTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(exitTargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitTargetLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(x)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        minimizeLabel.setBackground(new java.awt.Color(53, 53, 53));
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseExited(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText("_");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimizeLabelLayout = new javax.swing.GroupLayout(minimizeLabel);
        minimizeLabel.setLayout(minimizeLabelLayout);
        minimizeLabelLayout.setHorizontalGroup(
            minimizeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(minimizeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(minimizeLabelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(minimize)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        minimizeLabelLayout.setVerticalGroup(
            minimizeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(minimizeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(minimizeLabelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        helpLabel.setBackground(new java.awt.Color(53, 53, 53));
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpLabelMousePressed(evt);
            }
        });

        helpicon.setBackground(new java.awt.Color(53, 53, 53));
        helpicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/helpIcon.png"))); // NOI18N
        helpicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpiconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpiconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpiconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout helpLabelLayout = new javax.swing.GroupLayout(helpLabel);
        helpLabel.setLayout(helpLabelLayout);
        helpLabelLayout.setHorizontalGroup(
            helpLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLabelLayout.createSequentialGroup()
                .addComponent(helpicon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        helpLabelLayout.setVerticalGroup(
            helpLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpLabelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(helpicon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dragPanelLayout.createSequentialGroup()
                .addGap(0, 844, Short.MAX_VALUE)
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dragPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bg.add(dragPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        // TODO add your handling code here:
        Color fondo = new Color(153,0,0);
        exitTarget.setBackground(fondo);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        // TODO add your handling code here:
        exitTarget.setBackground(bg.getBackground());
    }//GEN-LAST:event_xMouseExited

    private void exitTargetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTargetMouseEntered
        // TODO add your handling code here:
        Color fondo = new Color(153,0,0);
        exitTarget.setBackground(fondo);
    }//GEN-LAST:event_exitTargetMouseEntered

    private void exitTargetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTargetMouseExited
        // TODO add your handling code here:
        exitTarget.setBackground(bg.getBackground());
    }//GEN-LAST:event_exitTargetMouseExited

    private void exitTargetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTargetMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitTargetMouseClicked

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_xMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:
        Color col = new Color (73,73,73);
        minimizeLabel.setBackground(col);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:
        minimizeLabel.setBackground(bg.getBackground());
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseEntered
        // TODO add your handling code here:
        Color col = new Color (73,73,73);
        minimizeLabel.setBackground(col);
    }//GEN-LAST:event_minimizeLabelMouseEntered

    private void minimizeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseExited
        // TODO add your handling code here:
        minimizeLabel.setBackground(bg.getBackground());
    }//GEN-LAST:event_minimizeLabelMouseExited

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void helpLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseEntered
        // TODO add your handling code here:
        Color col = new Color (73,73,73);
        helpLabel.setBackground(col);
    }//GEN-LAST:event_helpLabelMouseEntered

    private void helpLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseExited
        // TODO add your handling code here:
        helpLabel.setBackground(bg.getBackground());
    }//GEN-LAST:event_helpLabelMouseExited

    private void helpiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpiconMouseEntered
        // TODO add your handling code here:
        Color col = new Color (73,73,73);
        helpLabel.setBackground(col);
    }//GEN-LAST:event_helpiconMouseEntered

    private void helpiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpiconMouseExited
        // TODO add your handling code here:
        helpLabel.setBackground(bg.getBackground());
    }//GEN-LAST:event_helpiconMouseExited

    private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
        try {
            try {
                // TODO add your handling code here:
                Desktop.getDesktop().browse(new URI("https://rhmu.waifusmod.com"));
            } catch (IOException ex) {
                Logger.getLogger(logScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(logScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_helpLabelMouseClicked

    private void helpiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpiconMouseClicked
        // TODO add your handling code here:
        try {
            try {
                // TODO add your handling code here:
                Desktop.getDesktop().browse(new URI("https://rhmu.waifusmod.com"));
            } catch (IOException ex) {
                Logger.getLogger(logScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(logScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_helpiconMouseClicked

    private void dragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        Ymouse = evt.getY();
        
    }//GEN-LAST:event_dragPanelMousePressed

    private void dragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x -xMouse, y-Ymouse);
    }//GEN-LAST:event_dragPanelMouseDragged

    private void enterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterLabelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_enterLabelMouseClicked

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMousePressed
        // TODO add your handling code here:
        
        if (user.getText().equals("Ingrese su usuario")) {
            user.setText("");
        }
        if (String.valueOf(contrasena.getPassword()).isEmpty()) {
            contrasena.setText("**********");
        }
        
        
        
        
    }//GEN-LAST:event_userMousePressed

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_userMouseClicked

    private void contrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaMousePressed
        // TODO add your handling code here:
        if (String.valueOf(contrasena.getPassword()).equals("**********")) {
            contrasena.setText("");
        }
        if (user.getText().isEmpty()) {
            user.setText("Ingrese su usuario");
        }
    }//GEN-LAST:event_contrasenaMousePressed

    private void helpLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMousePressed
        // TODO add your handling code here:
        try {
            try {
                // TODO add your handling code here:
                Desktop.getDesktop().browse(new URI("https://rhmu.waifusmod.com"));
            } catch (IOException ex) {
                Logger.getLogger(logScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(logScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_helpLabelMousePressed

    private void helpiconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpiconMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpiconMousePressed

    private void enterLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterLabelMousePressed
        // TODO add your handling code here:
        
        try {
            conn= DriverManager.getConnection(url);
           
            if (user.getText().equals("Ingrese su usuario")|| String.valueOf(contrasena.getPassword()).equals("**********")|| user.getText().isEmpty()||String.valueOf(contrasena.getPassword()).isEmpty()) {
                JOptionPane.showMessageDialog(null, "Rellena los campos restantes");
                
            } else{
                if (conn!=null) {
                    PreparedStatement stmt = conn.prepareStatement("SELECT * FROM usuarios WHERE usuario =?");
                    stmt.setString(1, user.getText());
                    ResultSet rs = stmt.executeQuery();
                    System.out.println(String.valueOf(contrasena.getPassword()));
                    System.out.println(rs.getString("contrasena"));
                    if (!String.valueOf(contrasena.getPassword()).equals(rs.getString("contrasena"))) {
                        JOptionPane.showMessageDialog(null, "Contrasena incorrecta");
                    }
                    else{
                        String nombre = rs.getString("nombres");
                        p.setUser(nombre);
                        p.setVisible(true);
                        this.dispose();
                    }
                    
                    
                }
                
                
            
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e.getMessage(), "Error", 0);
        }finally{
             try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                System.err.println("Error al cerrar la conexión: " + e.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_enterLabelMousePressed

    private void registrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarMousePressed
        // TODO add your handling code here:
        registrarPanel r = new registrarPanel();
        r.setLocationRelativeTo(null);
        r.setVisible(true);
        
        
    }//GEN-LAST:event_registrarMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            FlatArcDarkIJTheme.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JPanel contrasenaLabel;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JLabel enterLabel;
    private javax.swing.JLabel eslogan;
    private javax.swing.JPanel exitTarget;
    private javax.swing.JPanel helpLabel;
    private javax.swing.JLabel helpicon;
    private javax.swing.JLabel inciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlabelContrasena;
    private javax.swing.JLabel jlabelUsuario;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JPanel leftLabel;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel minimizeLabel;
    private javax.swing.JLabel registrar;
    private javax.swing.JTextField user;
    private javax.swing.JPanel userLabel;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
