/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.screens;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author artur
 */
public class modificarPanel extends javax.swing.JPanel {
    DefaultTableModel modelo = new DefaultTableModel();
    Connection conn;
    String url = "jdbc:sqlite:C:\\Users\\artur\\Documents\\NetBeansProjects\\rhproyec\\src\\db_data\\data.db";
    boolean bander = false;
    /**
     * Creates new form modificarPanel
     */
    public modificarPanel() {
        
        initComponents();
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Sexo");
        modelo.addColumn("Area");
        modelo.addColumn("Sueldo");
        modelo.addColumn("Telefono");
        modelo.addColumn("Horario");
        modelo.addColumn("Horas");
        modelo.addColumn("Correo");
        modelo.addColumn("RFC");
        modelo.addColumn("NSS");
        modelo.addColumn("CURP");
        modelo.addColumn("SUPERVISOR");
        
        tabla.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconrhmu = new javax.swing.JLabel();
        tablaScrollPane = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        mostrarButton = new javax.swing.JButton();
        motivo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 35, 35));
        setPreferredSize(new java.awt.Dimension(1546, 876));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(1546, 876));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconrhmu.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        iconrhmu.setForeground(new java.awt.Color(255, 255, 255));
        iconrhmu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconrhmu.png"))); // NOI18N
        iconrhmu.setText("RH-MU El control es poder...");
        iconrhmu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(iconrhmu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 1050, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre completo", "Sexo", "Area", "Nss", "RFC", "Numero de telefono", "Area", "Sueldo", "Correo", "Horario", "Numero horas", "Curp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaScrollPane.setViewportView(tabla);

        jPanel1.add(tablaScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 1330, 540));

        mostrarButton.setBackground(new java.awt.Color(35, 81, 146));
        mostrarButton.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        mostrarButton.setText("Mostrar");
        mostrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, 120, 40));

        motivo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        motivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/motivo3.png"))); // NOI18N
        motivo.setPreferredSize(new java.awt.Dimension(1370, 411));
        jPanel1.add(motivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 650, 1550, 230));

        jLabel1.setBackground(new java.awt.Color(35, 81, 146));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recargar.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarButtonActionPerformed
        try {
            
            // TODO add your handling code here:
            conn = DriverManager.getConnection(url);
            PreparedStatement stmt = conn.prepareStatement("SELECT * FROM trabajador");
            ResultSet rs = stmt.executeQuery();
            if (bander==false) {
                while (rs.next()) {  
                int id = rs.getInt("id");
                String nombre = rs.getString("nombres")+" "+ rs.getString("apellidoP")+" "+rs.getString("apellidoM");
                String sexo = rs.getString("sexo"); String area = rs.getString("area"); Float sueldo = rs.getFloat("sueldo"); 
                String numero = rs.getString("num"); String horario = rs.getString("horario"); int horas = rs.getInt("numero_horas");
                String correo = rs.getString("correo"); String rfc= rs.getString("rfc");  String nss= rs.getString("nss"); String curp= rs.getString("curp");
                String supervisor = rs.getString("supervisor");
                Object [] datos = new Object[]{id,nombre,sexo,area,sueldo,numero, horario, horas, correo, rfc, nss, curp, supervisor};
                modelo.addRow(datos);
                
                }
                 bander=true;
            }
            
            if(bander==true){
                
                JOptionPane.showMessageDialog(null, "Ya mostraste todos los empleados", "Registro", 0);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(modificarPanel.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error " + ex.getMessage());
        }finally{
            try {
                if (conn!=null) {
                    conn.close();
                }
            } catch (Exception e) {
            }
        }
       
       
       
       
    }//GEN-LAST:event_mostrarButtonActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        modelo.getDataVector().removeAllElements();
        try {
            
            // TODO add your handling code here:
            conn = DriverManager.getConnection(url);
            PreparedStatement stmt = conn.prepareStatement("SELECT * FROM trabajador");
            ResultSet rs = stmt.executeQuery();
            
                while (rs.next()) {  
                int id = rs.getInt("id");
                String nombre = rs.getString("nombres")+" "+ rs.getString("apellidoP")+" "+rs.getString("apellidoM");
                String sexo = rs.getString("sexo"); String area = rs.getString("area"); Float sueldo = rs.getFloat("sueldo"); 
                String numero = rs.getString("num"); String horario = rs.getString("horario"); int horas = rs.getInt("numero_horas");
                String correo = rs.getString("correo"); String rfc= rs.getString("rfc");  String nss= rs.getString("nss"); String curp= rs.getString("curp");
                String supervisor = rs.getString("supervisor");
                Object [] datos = new Object[]{id,nombre,sexo,area,sueldo,numero, horario, horas, correo, rfc, nss, curp, supervisor};
                modelo.addRow(datos);
                
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(modificarPanel.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error " + ex.getMessage());
        }finally{
            try {
                if (conn!=null) {
                    conn.close();
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jLabel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconrhmu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarButton;
    private javax.swing.JLabel motivo;
    private javax.swing.JTable tabla;
    private javax.swing.JScrollPane tablaScrollPane;
    // End of variables declaration//GEN-END:variables
}
