/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.screens;

/**
 *
 * @author artur
 */
public class registrar extends javax.swing.JPanel {

    /**
     * Creates new form registrar
     */
    public registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eslogan = new javax.swing.JLabel();
        bienvenido = new javax.swing.JLabel();
        inciarSesion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contrasena = new javax.swing.JTextField();
        nombres = new javax.swing.JTextField();
        apellidoP = new javax.swing.JTextField();
        apellidoM = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        eslogan1 = new javax.swing.JLabel();
        bienvenido1 = new javax.swing.JLabel();
        inciarSesion1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        contrasena1 = new javax.swing.JTextField();
        nombres1 = new javax.swing.JTextField();
        apellidoP1 = new javax.swing.JTextField();
        apellidoM1 = new javax.swing.JTextField();
        correo1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(35, 81, 146));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eslogan.setFont(new java.awt.Font("Century Gothic", 2, 17)); // NOI18N
        eslogan.setForeground(new java.awt.Color(255, 255, 255));
        eslogan.setText("Control es poder...");
        add(eslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bienvenido.setBackground(new java.awt.Color(255, 255, 255));
        bienvenido.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        bienvenido.setText("Bienvenido");
        add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 40, -1, -1));

        inciarSesion.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        inciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        inciarSesion.setText("Iniciar sesion");
        add(inciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 84, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido Paterno");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido Materno");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        usuario.setBackground(new java.awt.Color(53, 53, 53));
        usuario.setBorder(null);
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, 20));

        contrasena.setBackground(new java.awt.Color(53, 53, 53));
        contrasena.setBorder(null);
        contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaActionPerformed(evt);
            }
        });
        add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 160, 20));

        nombres.setBackground(new java.awt.Color(53, 53, 53));
        nombres.setBorder(null);
        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });
        add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 150, 20));

        apellidoP.setBackground(new java.awt.Color(53, 53, 53));
        apellidoP.setBorder(null);
        apellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoPActionPerformed(evt);
            }
        });
        add(apellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 82, 20));

        apellidoM.setBackground(new java.awt.Color(53, 53, 53));
        apellidoM.setBorder(null);
        add(apellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 80, 20));

        correo.setBackground(new java.awt.Color(53, 53, 53));
        correo.setBorder(null);
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 170, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flechaButton.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Iniciar sesion");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 90, -1));

        jPanel1.setBackground(new java.awt.Color(35, 81, 146));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eslogan1.setFont(new java.awt.Font("Century Gothic", 2, 17)); // NOI18N
        eslogan1.setForeground(new java.awt.Color(255, 255, 255));
        eslogan1.setText("Control es poder...");
        jPanel1.add(eslogan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bienvenido1.setBackground(new java.awt.Color(255, 255, 255));
        bienvenido1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        bienvenido1.setForeground(new java.awt.Color(255, 255, 255));
        bienvenido1.setText("Bienvenido");
        jPanel1.add(bienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 40, -1, -1));

        inciarSesion1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        inciarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        inciarSesion1.setText("Iniciar sesion");
        jPanel1.add(inciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 84, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombres");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Apellido Paterno");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Apellido Materno");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Correo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        usuario1.setBackground(new java.awt.Color(53, 53, 53));
        usuario1.setBorder(null);
        usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario1ActionPerformed(evt);
            }
        });
        jPanel1.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, 20));

        contrasena1.setBackground(new java.awt.Color(53, 53, 53));
        contrasena1.setBorder(null);
        contrasena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasena1ActionPerformed(evt);
            }
        });
        jPanel1.add(contrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 160, 20));

        nombres1.setBackground(new java.awt.Color(53, 53, 53));
        nombres1.setBorder(null);
        nombres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombres1ActionPerformed(evt);
            }
        });
        jPanel1.add(nombres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 150, 20));

        apellidoP1.setBackground(new java.awt.Color(53, 53, 53));
        apellidoP1.setBorder(null);
        apellidoP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoP1ActionPerformed(evt);
            }
        });
        jPanel1.add(apellidoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 82, 20));

        apellidoM1.setBackground(new java.awt.Color(53, 53, 53));
        apellidoM1.setBorder(null);
        jPanel1.add(apellidoM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 80, 20));

        correo1.setBackground(new java.awt.Color(53, 53, 53));
        correo1.setBorder(null);
        correo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo1ActionPerformed(evt);
            }
        });
        jPanel1.add(correo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 170, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flechaButton.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Iniciar sesion");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 90, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaActionPerformed

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void apellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoPActionPerformed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario1ActionPerformed

    private void contrasena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasena1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasena1ActionPerformed

    private void nombres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombres1ActionPerformed

    private void apellidoP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoP1ActionPerformed

    private void correo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoM;
    private javax.swing.JTextField apellidoM1;
    private javax.swing.JTextField apellidoP;
    private javax.swing.JTextField apellidoP1;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel bienvenido1;
    private javax.swing.JTextField contrasena;
    private javax.swing.JTextField contrasena1;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField correo1;
    private javax.swing.JLabel eslogan;
    private javax.swing.JLabel eslogan1;
    private javax.swing.JLabel inciarSesion;
    private javax.swing.JLabel inciarSesion1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField nombres1;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField usuario1;
    // End of variables declaration//GEN-END:variables
}
